# Generated by Django 5.2.7 on 2026-01-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('request_id', models.CharField(editable=False, max_length=350, primary_key=True, serialize=False)),
                ('target_user_id', models.CharField(max_length=350)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=350, unique=True)),
                ('trans_code', models.CharField(max_length=350, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=9)),
                ('message', models.TextField(null=True)),
                ('trans_desc', models.TextField(null=True)),
                ('trans_type', models.CharField(choices=[('MPESASTKPUSH', 'MPESASTKPUSH')], max_length=12)),
                ('service_name', models.CharField(max_length=50)),
                ('reply_to', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitTransactions',
            fields=[
                ('trans_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('originator', models.CharField(choices=[('MPESASTKPUSH', 'MPESASTKPUSH')], max_length=50)),
                ('trans_type', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=255)),
                ('account_reference', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=350, null=True, unique=True)),
                ('trans_code', models.CharField(max_length=350, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('split_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.transactions')),
            ],
        ),
    ]
