# Generated by Django 5.2.7 on 2026-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='split',
            field=models.BooleanField(default=False),
        ),
    ]
