# Generated by Django 5.2.7 on 2026-01-10 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transactions_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittransactions',
            name='split_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.transactions'),
        ),
        migrations.AlterField(
            model_name='splittransactions',
            name='trans_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
