# Generated by Django 5.2.7 on 2026-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_splittransactions_split_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splittransactions',
            name='occassion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
