# Generated by Django 5.2.7 on 2026-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_splittransactions_occassion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittransactions',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'proccessed'), ('failedprocessing', 'failedprocessing'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=20),
        ),
    ]
