# Generated by Django 5.2.7 on 2026-01-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_splittransactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='splittransactions',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
