# Generated by Django 5.2.7 on 2026-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_splittransactions_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='splittransactions',
            name='trans_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
