# Generated by Django 5.2.13 on 2026-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_splittransactions_trans_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="reference_id",
            field=models.CharField(max_length=350, null=True, unique=True),
        ),
    ]
