# Generated by Django 5.2.13 on 2026-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_transactions_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="target_user_id",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
